/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const MeditationType = IDL.Variant({
  'ifs' : IDL.Null,
  'metta' : IDL.Null,
  'mindfulness' : IDL.Null,
  'visualization' : IDL.Null,
});
export const Ritual = IDL.Record({
  'duration' : IDL.Nat,
  'ambientSoundVolume' : IDL.Nat,
  'timestamp' : IDL.Int,
  'ambientSound' : IDL.Text,
  'meditationType' : MeditationType,
});
export const Book = IDL.Record({
  'title' : IDL.Text,
  'goodreadsLink' : IDL.Text,
  'icon' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'author' : IDL.Text,
});
export const MoodState = IDL.Variant({
  'sad' : IDL.Null,
  'anxious' : IDL.Null,
  'happy' : IDL.Null,
  'calm' : IDL.Null,
  'neutral' : IDL.Null,
});
export const EnergyState = IDL.Variant({
  'tired' : IDL.Null,
  'energized' : IDL.Null,
  'restless' : IDL.Null,
  'balanced' : IDL.Null,
});
export const JournalEntry = IDL.Record({
  'id' : IDL.Nat,
  'duration' : IDL.Nat,
  'mood' : IDL.Vec(MoodState),
  'user' : IDL.Principal,
  'isFavorite' : IDL.Bool,
  'timestamp' : IDL.Int,
  'reflection' : IDL.Text,
  'meditationType' : MeditationType,
  'energy' : EnergyState,
});
export const ProgressStats = IDL.Record({
  'monthlyMinutes' : IDL.Nat,
  'rank' : IDL.Text,
  'currentStreak' : IDL.Nat,
  'totalMinutes' : IDL.Nat,
});
export const MeditationSession = IDL.Record({
  'minutes' : IDL.Nat,
  'timestamp' : IDL.Int,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'avatar' : IDL.Opt(ExternalBlob),
});
export const ExportData = IDL.Record({
  'journalEntries' : IDL.Vec(JournalEntry),
  'progressStats' : ProgressStats,
  'sessionRecords' : IDL.Vec(MeditationSession),
  'userProfile' : IDL.Opt(UserProfile),
});
export const ImportData = IDL.Record({
  'journalEntries' : IDL.Vec(JournalEntry),
  'progressStats' : ProgressStats,
  'sessionRecords' : IDL.Vec(MeditationSession),
  'userProfile' : IDL.Opt(UserProfile),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteRitual' : IDL.Func([Ritual], [], []),
  'getBooks' : IDL.Func([], [IDL.Vec(Book)], ['query']),
  'getCallerJournalEntries' : IDL.Func([], [IDL.Vec(JournalEntry)], ['query']),
  'getCallerProgressStats' : IDL.Func([], [ProgressStats], ['query']),
  'getCallerSessionRecords' : IDL.Func(
      [],
      [IDL.Vec(MeditationSession)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCurrentUserExportData' : IDL.Func([], [ExportData], ['query']),
  'getDailyQuotes' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'importData' : IDL.Func([ImportData, IDL.Bool], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listCallerRituals' : IDL.Func([], [IDL.Vec(Ritual)], ['query']),
  'recordMeditationSession' : IDL.Func(
      [MeditationSession, IDL.Nat, IDL.Nat],
      [ProgressStats],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveRitual' : IDL.Func([Ritual], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const MeditationType = IDL.Variant({
    'ifs' : IDL.Null,
    'metta' : IDL.Null,
    'mindfulness' : IDL.Null,
    'visualization' : IDL.Null,
  });
  const Ritual = IDL.Record({
    'duration' : IDL.Nat,
    'ambientSoundVolume' : IDL.Nat,
    'timestamp' : IDL.Int,
    'ambientSound' : IDL.Text,
    'meditationType' : MeditationType,
  });
  const Book = IDL.Record({
    'title' : IDL.Text,
    'goodreadsLink' : IDL.Text,
    'icon' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'author' : IDL.Text,
  });
  const MoodState = IDL.Variant({
    'sad' : IDL.Null,
    'anxious' : IDL.Null,
    'happy' : IDL.Null,
    'calm' : IDL.Null,
    'neutral' : IDL.Null,
  });
  const EnergyState = IDL.Variant({
    'tired' : IDL.Null,
    'energized' : IDL.Null,
    'restless' : IDL.Null,
    'balanced' : IDL.Null,
  });
  const JournalEntry = IDL.Record({
    'id' : IDL.Nat,
    'duration' : IDL.Nat,
    'mood' : IDL.Vec(MoodState),
    'user' : IDL.Principal,
    'isFavorite' : IDL.Bool,
    'timestamp' : IDL.Int,
    'reflection' : IDL.Text,
    'meditationType' : MeditationType,
    'energy' : EnergyState,
  });
  const ProgressStats = IDL.Record({
    'monthlyMinutes' : IDL.Nat,
    'rank' : IDL.Text,
    'currentStreak' : IDL.Nat,
    'totalMinutes' : IDL.Nat,
  });
  const MeditationSession = IDL.Record({
    'minutes' : IDL.Nat,
    'timestamp' : IDL.Int,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'avatar' : IDL.Opt(ExternalBlob),
  });
  const ExportData = IDL.Record({
    'journalEntries' : IDL.Vec(JournalEntry),
    'progressStats' : ProgressStats,
    'sessionRecords' : IDL.Vec(MeditationSession),
    'userProfile' : IDL.Opt(UserProfile),
  });
  const ImportData = IDL.Record({
    'journalEntries' : IDL.Vec(JournalEntry),
    'progressStats' : ProgressStats,
    'sessionRecords' : IDL.Vec(MeditationSession),
    'userProfile' : IDL.Opt(UserProfile),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteRitual' : IDL.Func([Ritual], [], []),
    'getBooks' : IDL.Func([], [IDL.Vec(Book)], ['query']),
    'getCallerJournalEntries' : IDL.Func(
        [],
        [IDL.Vec(JournalEntry)],
        ['query'],
      ),
    'getCallerProgressStats' : IDL.Func([], [ProgressStats], ['query']),
    'getCallerSessionRecords' : IDL.Func(
        [],
        [IDL.Vec(MeditationSession)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCurrentUserExportData' : IDL.Func([], [ExportData], ['query']),
    'getDailyQuotes' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'importData' : IDL.Func([ImportData, IDL.Bool], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listCallerRituals' : IDL.Func([], [IDL.Vec(Ritual)], ['query']),
    'recordMeditationSession' : IDL.Func(
        [MeditationSession, IDL.Nat, IDL.Nat],
        [ProgressStats],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveRitual' : IDL.Func([Ritual], [], []),
  });
};

export const init = ({ IDL }) => { return []; };