/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Book {
  'title' : string,
  'goodreadsLink' : string,
  'icon' : string,
  'tags' : Array<string>,
  'description' : string,
  'author' : string,
}
export type EnergyState = { 'tired' : null } |
  { 'energized' : null } |
  { 'restless' : null } |
  { 'balanced' : null };
export interface ExportData {
  'journalEntries' : Array<JournalEntry>,
  'progressStats' : ProgressStats,
  'sessionRecords' : Array<MeditationSession>,
  'userProfile' : [] | [UserProfile],
}
export type ExternalBlob = Uint8Array;
export interface ImportData {
  'journalEntries' : Array<JournalEntry>,
  'progressStats' : ProgressStats,
  'sessionRecords' : Array<MeditationSession>,
  'userProfile' : [] | [UserProfile],
}
export interface JournalEntry {
  'id' : bigint,
  'duration' : bigint,
  'mood' : Array<MoodState>,
  'user' : Principal,
  'isFavorite' : boolean,
  'timestamp' : bigint,
  'reflection' : string,
  'meditationType' : MeditationType,
  'energy' : EnergyState,
}
export interface JournalEntryInput {
  'duration' : bigint,
  'mood' : Array<MoodState>,
  'isFavorite' : boolean,
  'timestamp' : bigint,
  'reflection' : string,
  'meditationType' : MeditationType,
  'energy' : EnergyState,
}
export interface MeditationSession { 'minutes' : bigint, 'timestamp' : bigint }
export type MeditationType = { 'ifs' : null } |
  { 'metta' : null } |
  { 'mindfulness' : null } |
  { 'visualization' : null };
export type MoodState = { 'sad' : null } |
  { 'anxious' : null } |
  { 'happy' : null } |
  { 'calm' : null } |
  { 'neutral' : null };
export interface ProgressStats {
  'monthlyMinutes' : bigint,
  'rank' : string,
  'currentStreak' : bigint,
  'totalMinutes' : bigint,
}
export interface Ritual {
  'duration' : bigint,
  'ambientSoundVolume' : bigint,
  'timestamp' : bigint,
  'ambientSound' : string,
  'meditationType' : MeditationType,
}
export interface UserProfile {
  'name' : string,
  'email' : [] | [string],
  'avatar' : [] | [ExternalBlob],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createJournalEntry' : ActorMethod<[JournalEntryInput], JournalEntry>,
  'deleteJournalEntry' : ActorMethod<[bigint], undefined>,
  'deleteRitual' : ActorMethod<[Ritual], undefined>,
  'editJournalEntry' : ActorMethod<[JournalEntryInput], JournalEntry>,
  'getBooks' : ActorMethod<[], Array<Book>>,
  'getCallerJournalEntries' : ActorMethod<[], Array<JournalEntry>>,
  'getCallerProgressStats' : ActorMethod<[], ProgressStats>,
  'getCallerSessionRecords' : ActorMethod<[], Array<MeditationSession>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCurrentUserExportData' : ActorMethod<[], ExportData>,
  'getDailyQuotes' : ActorMethod<[], Array<string>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'importData' : ActorMethod<[ImportData], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listCallerRituals' : ActorMethod<[], Array<Ritual>>,
  'recordMeditationSession' : ActorMethod<
    [MeditationSession, bigint, bigint],
    ProgressStats
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveRitual' : ActorMethod<[Ritual], undefined>,
  'toggleFavoriteEntry' : ActorMethod<[bigint], undefined>,
  'updateJournalEntry' : ActorMethod<[bigint, JournalEntryInput], JournalEntry>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];