/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface ExportData {
    journalEntries: Array<JournalEntry>;
    progressStats: ProgressStats;
    sessionRecords: Array<MeditationSession>;
    userProfile?: UserProfile;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Book {
    title: string;
    goodreadsLink: string;
    icon: string;
    tags: Array<string>;
    description: string;
    author: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface ProgressStats {
    monthlyMinutes: bigint;
    rank: string;
    currentStreak: bigint;
    totalMinutes: bigint;
}
export interface MeditationSession {
    minutes: bigint;
    timestamp: bigint;
}
export interface JournalEntry {
    id: bigint;
    duration: bigint;
    mood: Array<MoodState>;
    user: Principal;
    isFavorite: boolean;
    timestamp: bigint;
    reflection: string;
    meditationType: MeditationType;
    energy: EnergyState;
}
export interface Ritual {
    duration: bigint;
    ambientSoundVolume: bigint;
    timestamp: bigint;
    ambientSound: string;
    meditationType: MeditationType;
}
export interface ImportData {
    journalEntries: Array<JournalEntry>;
    progressStats: ProgressStats;
    sessionRecords: Array<MeditationSession>;
    userProfile?: UserProfile;
}
export interface JournalEntryInput {
    duration: bigint;
    mood: Array<MoodState>;
    isFavorite: boolean;
    timestamp: bigint;
    reflection: string;
    meditationType: MeditationType;
    energy: EnergyState;
}
export interface UserProfile {
    name: string;
    email?: string;
    avatar?: ExternalBlob;
}
export enum EnergyState {
    tired = "tired",
    energized = "energized",
    restless = "restless",
    balanced = "balanced"
}
export enum MeditationType {
    ifs = "ifs",
    metta = "metta",
    mindfulness = "mindfulness",
    visualization = "visualization"
}
export enum MoodState {
    sad = "sad",
    anxious = "anxious",
    happy = "happy",
    calm = "calm",
    neutral = "neutral"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createJournalEntry(entry: JournalEntryInput): Promise<JournalEntry>;
    deleteJournalEntry(entryId: bigint): Promise<void>;
    deleteRitual(ritual: Ritual): Promise<void>;
    editJournalEntry(entry: JournalEntryInput): Promise<JournalEntry>;
    getBooks(): Promise<Array<Book>>;
    getCallerJournalEntries(): Promise<Array<JournalEntry>>;
    getCallerProgressStats(): Promise<ProgressStats>;
    getCallerSessionRecords(): Promise<Array<MeditationSession>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCurrentUserExportData(): Promise<ExportData>;
    getDailyQuotes(): Promise<Array<string>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    importData(importData: ImportData): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    listCallerRituals(): Promise<Array<Ritual>>;
    recordMeditationSession(session: MeditationSession, _monthlyStats: bigint, _currentStreak: bigint): Promise<ProgressStats>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveRitual(ritual: Ritual): Promise<void>;
    toggleFavoriteEntry(entryId: bigint): Promise<void>;
    updateJournalEntry(entryId: bigint, entry: JournalEntryInput): Promise<JournalEntry>;
}
import type { EnergyState as _EnergyState, ExportData as _ExportData, ExternalBlob as _ExternalBlob, ImportData as _ImportData, JournalEntry as _JournalEntry, JournalEntryInput as _JournalEntryInput, MeditationSession as _MeditationSession, MeditationType as _MeditationType, MoodState as _MoodState, ProgressStats as _ProgressStats, Ritual as _Ritual, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createJournalEntry(arg0: JournalEntryInput): Promise<JournalEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.createJournalEntry(to_candid_JournalEntryInput_n10(this._uploadFile, this._downloadFile, arg0));
                return from_candid_JournalEntry_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createJournalEntry(to_candid_JournalEntryInput_n10(this._uploadFile, this._downloadFile, arg0));
            return from_candid_JournalEntry_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteJournalEntry(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteJournalEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteJournalEntry(arg0);
            return result;
        }
    }
    async deleteRitual(arg0: Ritual): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteRitual(to_candid_Ritual_n28(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteRitual(to_candid_Ritual_n28(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async editJournalEntry(arg0: JournalEntryInput): Promise<JournalEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.editJournalEntry(to_candid_JournalEntryInput_n10(this._uploadFile, this._downloadFile, arg0));
                return from_candid_JournalEntry_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editJournalEntry(to_candid_JournalEntryInput_n10(this._uploadFile, this._downloadFile, arg0));
            return from_candid_JournalEntry_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBooks(): Promise<Array<Book>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBooks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBooks();
            return result;
        }
    }
    async getCallerJournalEntries(): Promise<Array<JournalEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerJournalEntries();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerJournalEntries();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerProgressStats(): Promise<ProgressStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerProgressStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerProgressStats();
            return result;
        }
    }
    async getCallerSessionRecords(): Promise<Array<MeditationSession>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerSessionRecords();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerSessionRecords();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCurrentUserExportData(): Promise<ExportData> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentUserExportData();
                return from_candid_ExportData_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentUserExportData();
            return from_candid_ExportData_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDailyQuotes(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyQuotes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyQuotes();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async importData(arg0: ImportData): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.importData(await to_candid_ImportData_n41(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.importData(await to_candid_ImportData_n41(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listCallerRituals(): Promise<Array<Ritual>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCallerRituals();
                return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCallerRituals();
            return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async recordMeditationSession(arg0: MeditationSession, arg1: bigint, arg2: bigint): Promise<ProgressStats> {
        if (this.processError) {
            try {
                const result = await this.actor.recordMeditationSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordMeditationSession(arg0, arg1, arg2);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n46(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n46(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveRitual(arg0: Ritual): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveRitual(to_candid_Ritual_n28(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveRitual(to_candid_Ritual_n28(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async toggleFavoriteEntry(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleFavoriteEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleFavoriteEntry(arg0);
            return result;
        }
    }
    async updateJournalEntry(arg0: bigint, arg1: JournalEntryInput): Promise<JournalEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.updateJournalEntry(arg0, to_candid_JournalEntryInput_n10(this._uploadFile, this._downloadFile, arg1));
                return from_candid_JournalEntry_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateJournalEntry(arg0, to_candid_JournalEntryInput_n10(this._uploadFile, this._downloadFile, arg1));
            return from_candid_JournalEntry_n19(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_EnergyState_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EnergyState): EnergyState {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
async function from_candid_ExportData_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExportData): Promise<ExportData> {
    return await from_candid_record_n40(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_JournalEntry_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JournalEntry): JournalEntry {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_MeditationType_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MeditationType): MeditationType {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_MoodState_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MoodState): MoodState {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_Ritual_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Ritual): Ritual {
    return from_candid_record_n51(_uploadFile, _downloadFile, value);
}
async function from_candid_UserProfile_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): Promise<UserProfile> {
    return await from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): Promise<UserProfile | null> {
    return value.length === 0 ? null : await from_candid_UserProfile_n32(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n36(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    duration: bigint;
    mood: Array<_MoodState>;
    user: Principal;
    isFavorite: boolean;
    timestamp: bigint;
    reflection: string;
    meditationType: _MeditationType;
    energy: _EnergyState;
}): {
    id: bigint;
    duration: bigint;
    mood: Array<MoodState>;
    user: Principal;
    isFavorite: boolean;
    timestamp: bigint;
    reflection: string;
    meditationType: MeditationType;
    energy: EnergyState;
} {
    return {
        id: value.id,
        duration: value.duration,
        mood: from_candid_vec_n21(_uploadFile, _downloadFile, value.mood),
        user: value.user,
        isFavorite: value.isFavorite,
        timestamp: value.timestamp,
        reflection: value.reflection,
        meditationType: from_candid_MeditationType_n24(_uploadFile, _downloadFile, value.meditationType),
        energy: from_candid_EnergyState_n26(_uploadFile, _downloadFile, value.energy)
    };
}
async function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email: [] | [string];
    avatar: [] | [_ExternalBlob];
}): Promise<{
    name: string;
    email?: string;
    avatar?: ExternalBlob;
}> {
    return {
        name: value.name,
        email: record_opt_to_undefined(from_candid_opt_n34(_uploadFile, _downloadFile, value.email)),
        avatar: record_opt_to_undefined(await from_candid_opt_n35(_uploadFile, _downloadFile, value.avatar))
    };
}
async function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    journalEntries: Array<_JournalEntry>;
    progressStats: _ProgressStats;
    sessionRecords: Array<_MeditationSession>;
    userProfile: [] | [_UserProfile];
}): Promise<{
    journalEntries: Array<JournalEntry>;
    progressStats: ProgressStats;
    sessionRecords: Array<MeditationSession>;
    userProfile?: UserProfile;
}> {
    return {
        journalEntries: from_candid_vec_n30(_uploadFile, _downloadFile, value.journalEntries),
        progressStats: value.progressStats,
        sessionRecords: value.sessionRecords,
        userProfile: record_opt_to_undefined(await from_candid_opt_n31(_uploadFile, _downloadFile, value.userProfile))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    duration: bigint;
    ambientSoundVolume: bigint;
    timestamp: bigint;
    ambientSound: string;
    meditationType: _MeditationType;
}): {
    duration: bigint;
    ambientSoundVolume: bigint;
    timestamp: bigint;
    ambientSound: string;
    meditationType: MeditationType;
} {
    return {
        duration: value.duration,
        ambientSoundVolume: value.ambientSoundVolume,
        timestamp: value.timestamp,
        ambientSound: value.ambientSound,
        meditationType: from_candid_MeditationType_n24(_uploadFile, _downloadFile, value.meditationType)
    };
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sad: null;
} | {
    anxious: null;
} | {
    happy: null;
} | {
    calm: null;
} | {
    neutral: null;
}): MoodState {
    return "sad" in value ? MoodState.sad : "anxious" in value ? MoodState.anxious : "happy" in value ? MoodState.happy : "calm" in value ? MoodState.calm : "neutral" in value ? MoodState.neutral : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ifs: null;
} | {
    metta: null;
} | {
    mindfulness: null;
} | {
    visualization: null;
}): MeditationType {
    return "ifs" in value ? MeditationType.ifs : "metta" in value ? MeditationType.metta : "mindfulness" in value ? MeditationType.mindfulness : "visualization" in value ? MeditationType.visualization : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tired: null;
} | {
    energized: null;
} | {
    restless: null;
} | {
    balanced: null;
}): EnergyState {
    return "tired" in value ? EnergyState.tired : "energized" in value ? EnergyState.energized : "restless" in value ? EnergyState.restless : "balanced" in value ? EnergyState.balanced : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MoodState>): Array<MoodState> {
    return value.map((x)=>from_candid_MoodState_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_JournalEntry>): Array<JournalEntry> {
    return value.map((x)=>from_candid_JournalEntry_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Ritual>): Array<Ritual> {
    return value.map((x)=>from_candid_Ritual_n50(_uploadFile, _downloadFile, x));
}
function to_candid_EnergyState_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EnergyState): _EnergyState {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
async function to_candid_ImportData_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ImportData): Promise<_ImportData> {
    return await to_candid_record_n42(_uploadFile, _downloadFile, value);
}
function to_candid_JournalEntryInput_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JournalEntryInput): _JournalEntryInput {
    return to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_JournalEntry_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JournalEntry): _JournalEntry {
    return to_candid_record_n45(_uploadFile, _downloadFile, value);
}
function to_candid_MeditationType_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MeditationType): _MeditationType {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_MoodState_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MoodState): _MoodState {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_Ritual_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Ritual): _Ritual {
    return to_candid_record_n29(_uploadFile, _downloadFile, value);
}
async function to_candid_UserProfile_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): Promise<_UserProfile> {
    return await to_candid_record_n47(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    duration: bigint;
    mood: Array<MoodState>;
    isFavorite: boolean;
    timestamp: bigint;
    reflection: string;
    meditationType: MeditationType;
    energy: EnergyState;
}): {
    duration: bigint;
    mood: Array<_MoodState>;
    isFavorite: boolean;
    timestamp: bigint;
    reflection: string;
    meditationType: _MeditationType;
    energy: _EnergyState;
} {
    return {
        duration: value.duration,
        mood: to_candid_vec_n12(_uploadFile, _downloadFile, value.mood),
        isFavorite: value.isFavorite,
        timestamp: value.timestamp,
        reflection: value.reflection,
        meditationType: to_candid_MeditationType_n15(_uploadFile, _downloadFile, value.meditationType),
        energy: to_candid_EnergyState_n17(_uploadFile, _downloadFile, value.energy)
    };
}
function to_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    duration: bigint;
    ambientSoundVolume: bigint;
    timestamp: bigint;
    ambientSound: string;
    meditationType: MeditationType;
}): {
    duration: bigint;
    ambientSoundVolume: bigint;
    timestamp: bigint;
    ambientSound: string;
    meditationType: _MeditationType;
} {
    return {
        duration: value.duration,
        ambientSoundVolume: value.ambientSoundVolume,
        timestamp: value.timestamp,
        ambientSound: value.ambientSound,
        meditationType: to_candid_MeditationType_n15(_uploadFile, _downloadFile, value.meditationType)
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    journalEntries: Array<JournalEntry>;
    progressStats: ProgressStats;
    sessionRecords: Array<MeditationSession>;
    userProfile?: UserProfile;
}): Promise<{
    journalEntries: Array<_JournalEntry>;
    progressStats: _ProgressStats;
    sessionRecords: Array<_MeditationSession>;
    userProfile: [] | [_UserProfile];
}> {
    return {
        journalEntries: to_candid_vec_n43(_uploadFile, _downloadFile, value.journalEntries),
        progressStats: value.progressStats,
        sessionRecords: value.sessionRecords,
        userProfile: value.userProfile ? candid_some(await to_candid_UserProfile_n46(_uploadFile, _downloadFile, value.userProfile)) : candid_none()
    };
}
function to_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    duration: bigint;
    mood: Array<MoodState>;
    user: Principal;
    isFavorite: boolean;
    timestamp: bigint;
    reflection: string;
    meditationType: MeditationType;
    energy: EnergyState;
}): {
    id: bigint;
    duration: bigint;
    mood: Array<_MoodState>;
    user: Principal;
    isFavorite: boolean;
    timestamp: bigint;
    reflection: string;
    meditationType: _MeditationType;
    energy: _EnergyState;
} {
    return {
        id: value.id,
        duration: value.duration,
        mood: to_candid_vec_n12(_uploadFile, _downloadFile, value.mood),
        user: value.user,
        isFavorite: value.isFavorite,
        timestamp: value.timestamp,
        reflection: value.reflection,
        meditationType: to_candid_MeditationType_n15(_uploadFile, _downloadFile, value.meditationType),
        energy: to_candid_EnergyState_n17(_uploadFile, _downloadFile, value.energy)
    };
}
async function to_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email?: string;
    avatar?: ExternalBlob;
}): Promise<{
    name: string;
    email: [] | [string];
    avatar: [] | [_ExternalBlob];
}> {
    return {
        name: value.name,
        email: value.email ? candid_some(value.email) : candid_none(),
        avatar: value.avatar ? candid_some(await to_candid_ExternalBlob_n48(_uploadFile, _downloadFile, value.avatar)) : candid_none()
    };
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MoodState): {
    sad: null;
} | {
    anxious: null;
} | {
    happy: null;
} | {
    calm: null;
} | {
    neutral: null;
} {
    return value == MoodState.sad ? {
        sad: null
    } : value == MoodState.anxious ? {
        anxious: null
    } : value == MoodState.happy ? {
        happy: null
    } : value == MoodState.calm ? {
        calm: null
    } : value == MoodState.neutral ? {
        neutral: null
    } : value;
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MeditationType): {
    ifs: null;
} | {
    metta: null;
} | {
    mindfulness: null;
} | {
    visualization: null;
} {
    return value == MeditationType.ifs ? {
        ifs: null
    } : value == MeditationType.metta ? {
        metta: null
    } : value == MeditationType.mindfulness ? {
        mindfulness: null
    } : value == MeditationType.visualization ? {
        visualization: null
    } : value;
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EnergyState): {
    tired: null;
} | {
    energized: null;
} | {
    restless: null;
} | {
    balanced: null;
} {
    return value == EnergyState.tired ? {
        tired: null
    } : value == EnergyState.energized ? {
        energized: null
    } : value == EnergyState.restless ? {
        restless: null
    } : value == EnergyState.balanced ? {
        balanced: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<MoodState>): Array<_MoodState> {
    return value.map((x)=>to_candid_MoodState_n13(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<JournalEntry>): Array<_JournalEntry> {
    return value.map((x)=>to_candid_JournalEntry_n44(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
